# -*- coding: utf-8 -*-
"""Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1a3q99pK8u0oUrIukwT3aTvBqg5qEIe

# **Wine Quality Prediction Using Support Vector Mchine**

**Get understanding about Data Set**

White wine data has twelve variables

1.fixed acidity
2.volatile acidity
3.citric acid
4.residual sugar
5.chlorides
6.free sulphur dioxide
7.total sulphur dioxide
8.density
9.PH
10.sulphates
11.alcohol
12.quality

**import Library**
"""

import pandas as pd
import numpy as np

"""**Import CSV as DataFrame**"""

df = pd.read_csv(r"https://github.com/YBIFoundation/Dataset/raw/main/WhiteWineQuality.csv", sep=';')

"""**Describing Data**"""

df.head()

df.info()

df.describe()

df.columns

df.shape

#get unique values in y variable
df['quality'].value_counts()

df.groupby('quality').mean()

#define x and y variables
y = df['quality']
y.shape

y

x = df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

x.shape

x

#get x variables standardized
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

x = ss.fit_transform(x)
x

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, stratify=y, random_state=2529)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

"""**Get Train Model**"""

from sklearn.svm import SVC

svc = SVC()

svc.fit(x_train, y_train)

"""**Get Model Prediction**"""

y_pred = svc.predict(x_test)

y_pred.shape

y_pred

"""**Get Model Evaluation**"""

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

"""**Get Future Prediction**"""

df_new = df.sample(1)
df_new

df_new.shape

x_new = df_new.drop(['quality'], axis = 1)

x_new = ss.fit_transform(x_new)

y_pred_new = svc.predict(x_new)

y_pred_new

"""**Explanation**

# Predicting quality of wine using **support vector machine**
1. first we have taken the data , by using some functions we have descibed the data after that we defined x and y variables
2. split the data for training and testing purpose.
3. select the data to model here we used "support vector machine"
4. train and test the data  
5. predict the data
6. finally get the accuracy
"""